services:
  scanner: # Makefile
    build: ./src/Parser
    command: "bash"
    stdin_open: true
    tty: true
    working_dir: /app
    develop:
      watch:
        - path: ./src/Parser/
          action: sync+restart
          target: /app
    volumes:
      - ./src/Parser/:/app
