services:
  scanner: # Makefile
    build: ./src/Parser
    command: "bash"
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src/Parser/Build:/app/Build
      - ./src/Parser/Scanner:/app/Scanner
      - ./src/Parser/Parse:/app/Parse
