services:
  parser: # Makefile
    build: ./src/Parser
    command: "bash"
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src/Parser/Build:/app/Build
      - ./src/Parser/Scanner:/app/Scanner
      - ./src/Parser/Parse:/app/Parse
      - ./src/Parser/tests:/app/tests
      - ./src/Parser/Ast/:/app/Ast
      - ./src/Parser/Symbol/:/app/Symbol
