#!/bin/bash

# Variables
DIR=$(pwd)
CUP_PATH=/usr/share/java/cup.jar
BUILD_DIR=$(pwd)/Build

BINARY=Scanner

# Help
run() {
  printf "Help"
}

# Parse a tile
parse() {
  echo "java -cp "$CUP_PATH:$BUILD_DIR" $BINARY $1"

  java -cp "$CUP_PATH:$BUILD_DIR" $BINARY <$1
}

while getopts "r:s" opt; do
  case $opt in
  r)
    option=$OPTARG

    parse $option
    exit
    ;;
  esac
done

# Run the parser with only one option
if [[ $# -eq 1 ]]; then
  parse $1
fi
