#!/bin/bash

# Variables
DIR=$(pwd)
CUP_PATH=/usr/share/java/cup.jar
BUILD_DIR=$(pwd)/Build

SCANNER=Scanner
PARSER=Parser

# Help
help() {
  printf "./run | Run the current Parser/Scanner\n-h This help page\n-s [file] Scan a file and see the output\n"
}

# Scan a file
scan() {
  java -cp "$CUP_PATH:$BUILD_DIR" $SCANNER <$1
}

while getopts "sr:h" opt; do
  case $opt in
  h)
    help
    exit
    ;;

  s)
    option=$OPTARG

    scan $option
    exit
    ;;
  esac
done

# Run the parser with only one option
if [[ $# -eq 1 ]]; then
  scan $1
fi
